/**
 * Backfill readable SEO slugs on existing products.
 *
 * Old listings either have no slug or a timestamp-suffixed slug. This gives
 * them "brand-model-parttype-condition" slugs so /product/<slug> URLs are
 * human- and crawler-friendly. Old /product/<_id> URLs keep working because
 * the API resolves either form.
 *
 * Usage:
 *   set MONGODB_URI=...
 *   npm run backfill:slugs -- --dry-run
 *   npm run backfill:slugs
 *
 * Add --force to also rewrite slugs that already look clean.
 */

import dotenv from "dotenv";
import mongoose from "mongoose";
import { Product } from "../src/lib/models/Product";
import { buildProductSlugBase } from "../src/lib/products/productSlug";

dotenv.config();

function hasFlag(name: string) {
  return process.argv.includes(`--${name}`);
}

/** Timestamp-suffixed slugs from the previous generator. */
function looksAutoGenerated(slug?: string | null) {
  if (!slug) return true;
  return /-\d{13}$/.test(slug);
}

async function main() {
  const dryRun =
    hasFlag("dry-run") ||
    String(process.env.DRY_RUN || "").toLowerCase() === "true";
  const force = hasFlag("force");

  const uri =
    process.env.MONGODB_URI ||
    process.env.MONGO_URI ||
    process.env.DATABASE_URL;
  if (!uri) throw new Error("MONGODB_URI is required");

  await mongoose.connect(uri, {
    dbName: process.env.MONGODB_DB_NAME || "sparesx",
  });

  const products = await Product.find({})
    .select("_id brand deviceModel partType condition slug")
    .lean();

  const taken = new Set<string>(
    products
      .map((p) => p.slug)
      .filter((s): s is string => Boolean(s)),
  );

  let updated = 0;
  let skipped = 0;

  for (const product of products) {
    if (!force && !looksAutoGenerated(product.slug)) {
      skipped += 1;
      continue;
    }

    const base = buildProductSlugBase(product);
    let candidate = base;
    let counter = 2;
    while (taken.has(candidate) && candidate !== product.slug) {
      candidate = `${base}-${counter}`;
      counter += 1;
    }

    if (candidate === product.slug) {
      skipped += 1;
      continue;
    }

    if (product.slug) taken.delete(product.slug);
    taken.add(candidate);
    updated += 1;

    console.log(`${product.slug || "(none)"}  ->  ${candidate}`);

    if (!dryRun) {
      await Product.updateOne(
        { _id: product._id },
        { $set: { slug: candidate } },
      );
    }
  }

  console.log("\nSummary");
  console.log(`  Mode: ${dryRun ? "DRY RUN" : "APPLIED"}`);
  console.log(`  Products scanned: ${products.length}`);
  console.log(`  Slugs updated: ${updated}`);
  console.log(`  Skipped: ${skipped}`);

  await mongoose.disconnect();
}

main().catch(async (error) => {
  console.error("Backfill failed:", error?.message || error);
  try {
    await mongoose.disconnect();
  } catch {
    // ignore
  }
  process.exit(1);
});
